behaviors:
  PlayerBehavior:
    trainer_type: poca
    hyperparameters:
      batch_size: 256
      buffer_size: 51200
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 20000000
    time_horizon: 256
    summary_freq: 20000
    threaded: false
    self_play: null
    behavioral_cloning: null

env_settings:
  env_args: [
      --configPath,
      temp,
      --logPath,
      temp,
      --maEvalEpisodeLimit,
      100
    ]
  env_path: /app/MMORPG/2024/MA/Build/Build_linux_toy_hard_hetero_gstar/MMORPG.x86_64
  max_lifetime_restarts: 0
  num_envs: 1

engine_settings:
  time_scale: 20
  no_graphics: true

checkpoint_settings:
  run_id: temp
  results_dir: experiments/exp_02/results
  inference: true
  resume: true
  train_model: false
